---
- hosts: all
  connection: ssh
  tasks:
    - name: Getting tomcat installed from internet
      get_url:
         url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.105/bin/apache-tomcat-9.0.105.tar.gz"
         dest: "/root/"

    - name: UnZip the file
      command: tar -zxvf apache-tomcat-9.0.105.tar.gz

    - name: context.xml file
      copy:
       src: "/root/context.xml"
       dest: "/root/apache-tomcat-9.0.105/webapps/manager/META-INF/context.xml"

    - name: tomcat users
      copy:
        src: "/root/tomcat-users.xml"
        dest: "/root/apache-tomcat-9.0.105/conf/tomcat-users.xml"

    - name: starting tomcat
      shell: nohup /root/apache-tomcat-9.0.105/bin/startup.sh

...
